// src/core/events/eventTypes.ts

export const EVENTS = {
  /**
   * ORDER EVENTS
   */
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_UPDATED: "ORDER_UPDATED",

  /**
   * DRIVER EVENTS
   */
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  DRIVER_STATUS_UPDATED: "DRIVER_STATUS_UPDATED",

  /**
   * TRACKING EVENTS
   */
  TRACKING_UPDATED: "TRACKING_UPDATED",
  TRACKING_LOCATION_UPDATED: "TRACKING_LOCATION_UPDATED",

  /**
   * DELIVERY FLOW
   */
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",

  /**
   * WAREHOUSE EVENTS
   */
  WAREHOUSE_UPDATED: "WAREHOUSE_UPDATED",
  WAREHOUSE_CREATED: "WAREHOUSE_CREATED",
  WAREHOUSE_STOCK_UPDATED: "WAREHOUSE_STOCK_UPDATED",

  /**
   * PAYMENT EVENTS
   */
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
} as const;

export type EventType = keyof typeof EVENTS;